// auto-generated by yaml_to_cxx.py from test/upstream/regression/2766.yaml
#include "testlib.h"
void test_upstream_regression_2766() {
    enter_section("test_upstream_regression_2766: Stop people treating ptypes as objects");
    TEST_EQ(R::now()["epoch_time"].run(*conn), (err("RqlRuntimeError", "Cannot call `bracket` on objects of type `PTYPE<TIME>`.")));
    TEST_EQ(R::now().get_field("epoch_time").run(*conn), (err("RqlRuntimeError", "Cannot call `get_field` on objects of type `PTYPE<TIME>`.")));
    TEST_EQ(R::now().keys().run(*conn), (err("RqlRuntimeError", "Cannot call `keys` on objects of type `PTYPE<TIME>`.")));
    TEST_EQ(R::now().pluck("epoch_time").run(*conn), (err("RqlRuntimeError", "Cannot call `pluck` on objects of type `PTYPE<TIME>`.")));
    TEST_EQ(R::now().without("epoch_time").run(*conn), (err("RqlRuntimeError", "Cannot call `without` on objects of type `PTYPE<TIME>`.")));
    TEST_EQ(R::now().merge(R::object("foo", 4)).run(*conn), (err("RqlRuntimeError", "Cannot call `merge` on objects of type `PTYPE<TIME>`.")));
    TEST_EQ(R::expr(R::object("foo", 4)).merge(R::now()).run(*conn), (err("RqlRuntimeError", "Cannot merge objects of type `PTYPE<TIME>`.")));
    TEST_EQ(R::now().has_fields("epoch_time").run(*conn), (err("RqlRuntimeError", "Cannot call `has_fields` on objects of type `PTYPE<TIME>`.")));
    TEST_EQ(R::object().has_fields(R::time(2014, 7, 7, "Z")).run(*conn), (err("RqlRuntimeError", "Invalid path argument `1404691200`.")));
    TEST_EQ(R::expr(1).keys().run(*conn), (err("RqlRuntimeError", "Cannot call `keys` on objects of type `NUMBER`.")));
    exit_section();
}
